dist: focal
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-10
            - ninja-build
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "deb https://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
            - ninja-build
            - doxygen
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make
  - make test
  - make target=playground
  - make target=sample-project
  - make doc
