dist: xenial
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
            - ninja-build
            - doxygen
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make
  - make test
  - make target=playground
  - make target=sample-project
  - make doc
